(* File auto-generated by obus-gen-interface, DO NOT EDIT. *)
open OBus_value
open OBus_value.C
open OBus_member
open OBus_object
module Com_canonical_dbusmenu =
struct
  let interface = "com.canonical.dbusmenu"
  let m_AboutToShow = {
    Method.interface = interface;
    Method.member = "AboutToShow";
    Method.i_args = (arg1
                       (Some "id", basic_int32));
    Method.o_args = (arg1
                       (Some "needUpdate", basic_boolean));
    Method.annotations = [];
  }
  let m_AboutToShowGroup = {
    Method.interface = interface;
    Method.member = "AboutToShowGroup";
    Method.i_args = (arg1
                       (Some "ids", array basic_int32));
    Method.o_args = (arg2
                       (Some "updatesNeeded", array basic_int32)
                       (Some "idErrors", array basic_int32));
    Method.annotations = [];
  }
  let m_Event = {
    Method.interface = interface;
    Method.member = "Event";
    Method.i_args = (arg4
                       (Some "id", basic_int32)
                       (Some "eventId", basic_string)
                       (Some "data", variant)
                       (Some "timestamp", basic_uint32));
    Method.o_args = (arg0);
    Method.annotations = [];
  }
  let m_EventGroup = {
    Method.interface = interface;
    Method.member = "EventGroup";
    Method.i_args = (arg1
                       (Some "events", array (structure (seq4 basic_int32 basic_string variant basic_uint32))));
    Method.o_args = (arg1
                       (Some "idErrors", array basic_int32));
    Method.annotations = [];
  }
  let m_GetGroupProperties = {
    Method.interface = interface;
    Method.member = "GetGroupProperties";
    Method.i_args = (arg2
                       (Some "ids", array basic_int32)
                       (Some "propertyNames", array basic_string));
    Method.o_args = (arg1
                       (Some "properties", array (structure (seq2 basic_int32 (dict string variant)))));
    Method.annotations = [];
  }
  let m_GetLayout = {
    Method.interface = interface;
    Method.member = "GetLayout";
    Method.i_args = (arg3
                       (Some "parentId", basic_int32)
                       (Some "recursionDepth", basic_int32)
                       (Some "propertyNames", array basic_string));
    Method.o_args = (arg2
                       (Some "revision", basic_uint32)
                       (Some "layout", structure (seq3 basic_int32 (dict string variant) (array variant))));
    Method.annotations = [];
  }
  let m_GetProperty = {
    Method.interface = interface;
    Method.member = "GetProperty";
    Method.i_args = (arg2
                       (Some "id", basic_int32)
                       (Some "name", basic_string));
    Method.o_args = (arg1
                       (Some "value", variant));
    Method.annotations = [];
  }
  let s_ItemActivationRequested = {
    Signal.interface = interface;
    Signal.member = "ItemActivationRequested";
    Signal.args = (arg2
                       (Some "id", basic_int32)
                       (Some "timestamp", basic_uint32));
    Signal.annotations = [];
  }
  let s_ItemsPropertiesUpdated = {
    Signal.interface = interface;
    Signal.member = "ItemsPropertiesUpdated";
    Signal.args = (arg2
                       (Some "updatedProps", array (structure (seq2 basic_int32 (dict string variant))))
                       (Some "removedProps", array (structure (seq2 basic_int32 (array basic_string)))));
    Signal.annotations = [];
  }
  let s_LayoutUpdated = {
    Signal.interface = interface;
    Signal.member = "LayoutUpdated";
    Signal.args = (arg2
                       (Some "revision", basic_uint32)
                       (Some "parent", basic_int32));
    Signal.annotations = [];
  }
  let p_IconThemePath = {
    Property.interface = interface;
    Property.member = "IconThemePath";
    Property.typ = array basic_string;
    Property.access = Property.readable;
    Property.annotations = [];
  }
  let p_Status = {
    Property.interface = interface;
    Property.member = "Status";
    Property.typ = basic_string;
    Property.access = Property.readable;
    Property.annotations = [];
  }
  let p_TextDirection = {
    Property.interface = interface;
    Property.member = "TextDirection";
    Property.typ = basic_string;
    Property.access = Property.readable;
    Property.annotations = [];
  }
  let p_Version = {
    Property.interface = interface;
    Property.member = "Version";
    Property.typ = basic_uint32;
    Property.access = Property.readable;
    Property.annotations = [];
  }
  type 'a members = {
    m_AboutToShow : 'a OBus_object.t -> int32 -> bool Lwt.t;
    m_AboutToShowGroup : 'a OBus_object.t -> int32 list -> (int32 list * int32 list) Lwt.t;
    m_Event : 'a OBus_object.t -> int32 * string * OBus_value.V.single * int32 -> unit Lwt.t;
    m_EventGroup : 'a OBus_object.t -> (int32 * string * OBus_value.V.single * int32) list -> int32 list Lwt.t;
    m_GetGroupProperties : 'a OBus_object.t -> int32 list * string list -> (int32 * (string * OBus_value.V.single) list) list Lwt.t;
    m_GetLayout : 'a OBus_object.t -> int32 * int32 * string list -> (int32 * (int32 * (string * OBus_value.V.single) list * OBus_value.V.single list)) Lwt.t;
    m_GetProperty : 'a OBus_object.t -> int32 * string -> OBus_value.V.single Lwt.t;
    p_IconThemePath : 'a OBus_object.t -> string list React.signal;
    p_Status : 'a OBus_object.t -> string React.signal;
    p_TextDirection : 'a OBus_object.t -> string React.signal;
    p_Version : 'a OBus_object.t -> int32 React.signal;
  }
  let make members =
    OBus_object.make_interface_unsafe interface
      [
      ]
      [|
        method_info m_AboutToShow members.m_AboutToShow;
        method_info m_AboutToShowGroup members.m_AboutToShowGroup;
        method_info m_Event members.m_Event;
        method_info m_EventGroup members.m_EventGroup;
        method_info m_GetGroupProperties members.m_GetGroupProperties;
        method_info m_GetLayout members.m_GetLayout;
        method_info m_GetProperty members.m_GetProperty;
      |]
      [|
        signal_info s_ItemActivationRequested;
        signal_info s_ItemsPropertiesUpdated;
        signal_info s_LayoutUpdated;
      |]
      [|
        property_r_info p_IconThemePath members.p_IconThemePath;
        property_r_info p_Status members.p_Status;
        property_r_info p_TextDirection members.p_TextDirection;
        property_r_info p_Version members.p_Version;
      |]
end
module Org_kde_StatusNotifierItem =
struct
  let interface = "org.kde.StatusNotifierItem"
  let m_Scroll = {
    Method.interface = interface;
    Method.member = "Scroll";
    Method.i_args = (arg2
                       (Some "delta", basic_int32)
                       (Some "orientation", basic_string));
    Method.o_args = (arg0);
    Method.annotations = [];
  }
  let m_SecondaryActivate = {
    Method.interface = interface;
    Method.member = "SecondaryActivate";
    Method.i_args = (arg2
                       (Some "x", basic_int32)
                       (Some "y", basic_int32));
    Method.o_args = (arg0);
    Method.annotations = [];
  }
  let m_XAyatanaSecondaryActivate = {
    Method.interface = interface;
    Method.member = "XAyatanaSecondaryActivate";
    Method.i_args = (arg1
                       (Some "timestamp", basic_uint32));
    Method.o_args = (arg0);
    Method.annotations = [];
  }
  let s_NewAttentionIcon = {
    Signal.interface = interface;
    Signal.member = "NewAttentionIcon";
    Signal.args = (arg0);
    Signal.annotations = [];
  }
  let s_NewIcon = {
    Signal.interface = interface;
    Signal.member = "NewIcon";
    Signal.args = (arg0);
    Signal.annotations = [];
  }
  let s_NewIconThemePath = {
    Signal.interface = interface;
    Signal.member = "NewIconThemePath";
    Signal.args = (arg1
                       (Some "icon_theme_path", basic_string));
    Signal.annotations = [];
  }
  let s_NewStatus = {
    Signal.interface = interface;
    Signal.member = "NewStatus";
    Signal.args = (arg1
                       (Some "status", basic_string));
    Signal.annotations = [];
  }
  let s_NewTitle = {
    Signal.interface = interface;
    Signal.member = "NewTitle";
    Signal.args = (arg0);
    Signal.annotations = [];
  }
  let s_XAyatanaNewLabel = {
    Signal.interface = interface;
    Signal.member = "XAyatanaNewLabel";
    Signal.args = (arg2
                       (Some "label", basic_string)
                       (Some "guide", basic_string));
    Signal.annotations = [];
  }
  let p_AttentionAccessibleDesc = {
    Property.interface = interface;
    Property.member = "AttentionAccessibleDesc";
    Property.typ = basic_string;
    Property.access = Property.readable;
    Property.annotations = [];
  }
  let p_AttentionIconName = {
    Property.interface = interface;
    Property.member = "AttentionIconName";
    Property.typ = basic_string;
    Property.access = Property.readable;
    Property.annotations = [];
  }
  let p_Category = {
    Property.interface = interface;
    Property.member = "Category";
    Property.typ = basic_string;
    Property.access = Property.readable;
    Property.annotations = [];
  }
  let p_IconAccessibleDesc = {
    Property.interface = interface;
    Property.member = "IconAccessibleDesc";
    Property.typ = basic_string;
    Property.access = Property.readable;
    Property.annotations = [];
  }
  let p_IconName = {
    Property.interface = interface;
    Property.member = "IconName";
    Property.typ = basic_string;
    Property.access = Property.readable;
    Property.annotations = [];
  }
  let p_IconThemePath = {
    Property.interface = interface;
    Property.member = "IconThemePath";
    Property.typ = basic_string;
    Property.access = Property.readable;
    Property.annotations = [];
  }
  let p_Id = {
    Property.interface = interface;
    Property.member = "Id";
    Property.typ = basic_string;
    Property.access = Property.readable;
    Property.annotations = [];
  }
  let p_Menu = {
    Property.interface = interface;
    Property.member = "Menu";
    Property.typ = basic_object_path;
    Property.access = Property.readable;
    Property.annotations = [];
  }
  let p_Status = {
    Property.interface = interface;
    Property.member = "Status";
    Property.typ = basic_string;
    Property.access = Property.readable;
    Property.annotations = [];
  }
  let p_Title = {
    Property.interface = interface;
    Property.member = "Title";
    Property.typ = basic_string;
    Property.access = Property.readable;
    Property.annotations = [];
  }
  let p_XAyatanaLabel = {
    Property.interface = interface;
    Property.member = "XAyatanaLabel";
    Property.typ = basic_string;
    Property.access = Property.readable;
    Property.annotations = [];
  }
  let p_XAyatanaLabelGuide = {
    Property.interface = interface;
    Property.member = "XAyatanaLabelGuide";
    Property.typ = basic_string;
    Property.access = Property.readable;
    Property.annotations = [];
  }
  let p_XAyatanaOrderingIndex = {
    Property.interface = interface;
    Property.member = "XAyatanaOrderingIndex";
    Property.typ = basic_uint32;
    Property.access = Property.readable;
    Property.annotations = [];
  }
  type 'a members = {
    m_Scroll : 'a OBus_object.t -> int32 * string -> unit Lwt.t;
    m_SecondaryActivate : 'a OBus_object.t -> int32 * int32 -> unit Lwt.t;
    m_XAyatanaSecondaryActivate : 'a OBus_object.t -> int32 -> unit Lwt.t;
    p_AttentionAccessibleDesc : 'a OBus_object.t -> string React.signal;
    p_AttentionIconName : 'a OBus_object.t -> string React.signal;
    p_Category : 'a OBus_object.t -> string React.signal;
    p_IconAccessibleDesc : 'a OBus_object.t -> string React.signal;
    p_IconName : 'a OBus_object.t -> string React.signal;
    p_IconThemePath : 'a OBus_object.t -> string React.signal;
    p_Id : 'a OBus_object.t -> string React.signal;
    p_Menu : 'a OBus_object.t -> OBus_path.t React.signal;
    p_Status : 'a OBus_object.t -> string React.signal;
    p_Title : 'a OBus_object.t -> string React.signal;
    p_XAyatanaLabel : 'a OBus_object.t -> string React.signal;
    p_XAyatanaLabelGuide : 'a OBus_object.t -> string React.signal;
    p_XAyatanaOrderingIndex : 'a OBus_object.t -> int32 React.signal;
  }
  let make members =
    OBus_object.make_interface_unsafe interface
      [
      ]
      [|
        method_info m_Scroll members.m_Scroll;
        method_info m_SecondaryActivate members.m_SecondaryActivate;
        method_info m_XAyatanaSecondaryActivate members.m_XAyatanaSecondaryActivate;
      |]
      [|
        signal_info s_NewAttentionIcon;
        signal_info s_NewIcon;
        signal_info s_NewIconThemePath;
        signal_info s_NewStatus;
        signal_info s_NewTitle;
        signal_info s_XAyatanaNewLabel;
      |]
      [|
        property_r_info p_AttentionAccessibleDesc members.p_AttentionAccessibleDesc;
        property_r_info p_AttentionIconName members.p_AttentionIconName;
        property_r_info p_Category members.p_Category;
        property_r_info p_IconAccessibleDesc members.p_IconAccessibleDesc;
        property_r_info p_IconName members.p_IconName;
        property_r_info p_IconThemePath members.p_IconThemePath;
        property_r_info p_Id members.p_Id;
        property_r_info p_Menu members.p_Menu;
        property_r_info p_Status members.p_Status;
        property_r_info p_Title members.p_Title;
        property_r_info p_XAyatanaLabel members.p_XAyatanaLabel;
        property_r_info p_XAyatanaLabelGuide members.p_XAyatanaLabelGuide;
        property_r_info p_XAyatanaOrderingIndex members.p_XAyatanaOrderingIndex;
      |]
end
module Org_mpris_MediaPlayer2 =
struct
  let interface = "org.mpris.MediaPlayer2"
  let m_Quit = {
    Method.interface = interface;
    Method.member = "Quit";
    Method.i_args = (arg0);
    Method.o_args = (arg0);
    Method.annotations = [];
  }
  let m_Raise = {
    Method.interface = interface;
    Method.member = "Raise";
    Method.i_args = (arg0);
    Method.o_args = (arg0);
    Method.annotations = [];
  }
  let p_CanQuit = {
    Property.interface = interface;
    Property.member = "CanQuit";
    Property.typ = basic_boolean;
    Property.access = Property.readable;
    Property.annotations = [];
  }
  let p_CanRaise = {
    Property.interface = interface;
    Property.member = "CanRaise";
    Property.typ = basic_boolean;
    Property.access = Property.readable;
    Property.annotations = [];
  }
  let p_CanSetFullscreen = {
    Property.interface = interface;
    Property.member = "CanSetFullscreen";
    Property.typ = basic_boolean;
    Property.access = Property.readable;
    Property.annotations = [];
  }
  let p_DesktopEntry = {
    Property.interface = interface;
    Property.member = "DesktopEntry";
    Property.typ = basic_string;
    Property.access = Property.readable;
    Property.annotations = [];
  }
  let p_HasTrackList = {
    Property.interface = interface;
    Property.member = "HasTrackList";
    Property.typ = basic_boolean;
    Property.access = Property.readable;
    Property.annotations = [];
  }
  let p_Identity = {
    Property.interface = interface;
    Property.member = "Identity";
    Property.typ = basic_string;
    Property.access = Property.readable;
    Property.annotations = [];
  }
  let p_SupportedMimeTypes = {
    Property.interface = interface;
    Property.member = "SupportedMimeTypes";
    Property.typ = array basic_string;
    Property.access = Property.readable;
    Property.annotations = [];
  }
  let p_SupportedUriSchemes = {
    Property.interface = interface;
    Property.member = "SupportedUriSchemes";
    Property.typ = array basic_string;
    Property.access = Property.readable;
    Property.annotations = [];
  }
  type 'a members = {
    m_Quit : 'a OBus_object.t -> unit -> unit Lwt.t;
    m_Raise : 'a OBus_object.t -> unit -> unit Lwt.t;
    p_CanQuit : 'a OBus_object.t -> bool React.signal;
    p_CanRaise : 'a OBus_object.t -> bool React.signal;
    p_CanSetFullscreen : 'a OBus_object.t -> bool React.signal;
    p_DesktopEntry : 'a OBus_object.t -> string React.signal;
    p_HasTrackList : 'a OBus_object.t -> bool React.signal;
    p_Identity : 'a OBus_object.t -> string React.signal;
    p_SupportedMimeTypes : 'a OBus_object.t -> string list React.signal;
    p_SupportedUriSchemes : 'a OBus_object.t -> string list React.signal;
  }
  let make members =
    OBus_object.make_interface_unsafe interface
      [
      ]
      [|
        method_info m_Quit members.m_Quit;
        method_info m_Raise members.m_Raise;
      |]
      [|
      |]
      [|
        property_r_info p_CanQuit members.p_CanQuit;
        property_r_info p_CanRaise members.p_CanRaise;
        property_r_info p_CanSetFullscreen members.p_CanSetFullscreen;
        property_r_info p_DesktopEntry members.p_DesktopEntry;
        property_r_info p_HasTrackList members.p_HasTrackList;
        property_r_info p_Identity members.p_Identity;
        property_r_info p_SupportedMimeTypes members.p_SupportedMimeTypes;
        property_r_info p_SupportedUriSchemes members.p_SupportedUriSchemes;
      |]
end
module Org_mpris_MediaPlayer2_Player =
struct
  let interface = "org.mpris.MediaPlayer2.Player"
  let m_Next = {
    Method.interface = interface;
    Method.member = "Next";
    Method.i_args = (arg0);
    Method.o_args = (arg0);
    Method.annotations = [];
  }
  let m_OpenUri = {
    Method.interface = interface;
    Method.member = "OpenUri";
    Method.i_args = (arg1
                       (Some "Uri", basic_string));
    Method.o_args = (arg0);
    Method.annotations = [];
  }
  let m_Pause = {
    Method.interface = interface;
    Method.member = "Pause";
    Method.i_args = (arg0);
    Method.o_args = (arg0);
    Method.annotations = [];
  }
  let m_Play = {
    Method.interface = interface;
    Method.member = "Play";
    Method.i_args = (arg0);
    Method.o_args = (arg0);
    Method.annotations = [];
  }
  let m_PlayPause = {
    Method.interface = interface;
    Method.member = "PlayPause";
    Method.i_args = (arg0);
    Method.o_args = (arg0);
    Method.annotations = [];
  }
  let m_Previous = {
    Method.interface = interface;
    Method.member = "Previous";
    Method.i_args = (arg0);
    Method.o_args = (arg0);
    Method.annotations = [];
  }
  let m_Seek = {
    Method.interface = interface;
    Method.member = "Seek";
    Method.i_args = (arg1
                       (Some "Offset", basic_int64));
    Method.o_args = (arg0);
    Method.annotations = [];
  }
  let m_SetPosition = {
    Method.interface = interface;
    Method.member = "SetPosition";
    Method.i_args = (arg2
                       (Some "TrackId", basic_object_path)
                       (Some "Position", basic_int64));
    Method.o_args = (arg0);
    Method.annotations = [];
  }
  let m_Stop = {
    Method.interface = interface;
    Method.member = "Stop";
    Method.i_args = (arg0);
    Method.o_args = (arg0);
    Method.annotations = [];
  }
  let s_Seeked = {
    Signal.interface = interface;
    Signal.member = "Seeked";
    Signal.args = (arg1
                       (Some "Position", basic_int64));
    Signal.annotations = [];
  }
  let p_CanControl = {
    Property.interface = interface;
    Property.member = "CanControl";
    Property.typ = basic_boolean;
    Property.access = Property.readable;
    Property.annotations = [];
  }
  let p_CanGoNext = {
    Property.interface = interface;
    Property.member = "CanGoNext";
    Property.typ = basic_boolean;
    Property.access = Property.readable;
    Property.annotations = [];
  }
  let p_CanGoPrevious = {
    Property.interface = interface;
    Property.member = "CanGoPrevious";
    Property.typ = basic_boolean;
    Property.access = Property.readable;
    Property.annotations = [];
  }
  let p_CanPause = {
    Property.interface = interface;
    Property.member = "CanPause";
    Property.typ = basic_boolean;
    Property.access = Property.readable;
    Property.annotations = [];
  }
  let p_CanPlay = {
    Property.interface = interface;
    Property.member = "CanPlay";
    Property.typ = basic_boolean;
    Property.access = Property.readable;
    Property.annotations = [];
  }
  let p_CanSeek = {
    Property.interface = interface;
    Property.member = "CanSeek";
    Property.typ = basic_boolean;
    Property.access = Property.readable;
    Property.annotations = [];
  }
  let p_LoopStatus = {
    Property.interface = interface;
    Property.member = "LoopStatus";
    Property.typ = basic_string;
    Property.access = Property.readable_writable;
    Property.annotations = [];
  }
  let p_MaximumRate = {
    Property.interface = interface;
    Property.member = "MaximumRate";
    Property.typ = basic_double;
    Property.access = Property.readable;
    Property.annotations = [];
  }
  let p_Metadata = {
    Property.interface = interface;
    Property.member = "Metadata";
    Property.typ = dict string variant;
    Property.access = Property.readable;
    Property.annotations = [];
  }
  let p_MinimumRate = {
    Property.interface = interface;
    Property.member = "MinimumRate";
    Property.typ = basic_double;
    Property.access = Property.readable;
    Property.annotations = [];
  }
  let p_PlaybackStatus = {
    Property.interface = interface;
    Property.member = "PlaybackStatus";
    Property.typ = basic_string;
    Property.access = Property.readable;
    Property.annotations = [];
  }
  let p_Position = {
    Property.interface = interface;
    Property.member = "Position";
    Property.typ = basic_int64;
    Property.access = Property.readable;
    Property.annotations = [];
  }
  let p_Rate = {
    Property.interface = interface;
    Property.member = "Rate";
    Property.typ = basic_double;
    Property.access = Property.readable_writable;
    Property.annotations = [];
  }
  let p_Shuffle = {
    Property.interface = interface;
    Property.member = "Shuffle";
    Property.typ = basic_boolean;
    Property.access = Property.readable_writable;
    Property.annotations = [];
  }
  let p_Volume = {
    Property.interface = interface;
    Property.member = "Volume";
    Property.typ = basic_double;
    Property.access = Property.readable_writable;
    Property.annotations = [];
  }
  type 'a members = {
    m_Next : 'a OBus_object.t -> unit -> unit Lwt.t;
    m_OpenUri : 'a OBus_object.t -> string -> unit Lwt.t;
    m_Pause : 'a OBus_object.t -> unit -> unit Lwt.t;
    m_Play : 'a OBus_object.t -> unit -> unit Lwt.t;
    m_PlayPause : 'a OBus_object.t -> unit -> unit Lwt.t;
    m_Previous : 'a OBus_object.t -> unit -> unit Lwt.t;
    m_Seek : 'a OBus_object.t -> int64 -> unit Lwt.t;
    m_SetPosition : 'a OBus_object.t -> OBus_path.t * int64 -> unit Lwt.t;
    m_Stop : 'a OBus_object.t -> unit -> unit Lwt.t;
    p_CanControl : 'a OBus_object.t -> bool React.signal;
    p_CanGoNext : 'a OBus_object.t -> bool React.signal;
    p_CanGoPrevious : 'a OBus_object.t -> bool React.signal;
    p_CanPause : 'a OBus_object.t -> bool React.signal;
    p_CanPlay : 'a OBus_object.t -> bool React.signal;
    p_CanSeek : 'a OBus_object.t -> bool React.signal;
    p_LoopStatus : ('a OBus_object.t -> string React.signal) * ('a OBus_object.t -> string -> unit Lwt.t);
    p_MaximumRate : 'a OBus_object.t -> float React.signal;
    p_Metadata : 'a OBus_object.t -> (string * OBus_value.V.single) list React.signal;
    p_MinimumRate : 'a OBus_object.t -> float React.signal;
    p_PlaybackStatus : 'a OBus_object.t -> string React.signal;
    p_Position : 'a OBus_object.t -> int64 React.signal;
    p_Rate : ('a OBus_object.t -> float React.signal) * ('a OBus_object.t -> float -> unit Lwt.t);
    p_Shuffle : ('a OBus_object.t -> bool React.signal) * ('a OBus_object.t -> bool -> unit Lwt.t);
    p_Volume : ('a OBus_object.t -> float React.signal) * ('a OBus_object.t -> float -> unit Lwt.t);
  }
  let make members =
    OBus_object.make_interface_unsafe interface
      [
      ]
      [|
        method_info m_Next members.m_Next;
        method_info m_OpenUri members.m_OpenUri;
        method_info m_Pause members.m_Pause;
        method_info m_Play members.m_Play;
        method_info m_PlayPause members.m_PlayPause;
        method_info m_Previous members.m_Previous;
        method_info m_Seek members.m_Seek;
        method_info m_SetPosition members.m_SetPosition;
        method_info m_Stop members.m_Stop;
      |]
      [|
        signal_info s_Seeked;
      |]
      [|
        property_r_info p_CanControl members.p_CanControl;
        property_r_info p_CanGoNext members.p_CanGoNext;
        property_r_info p_CanGoPrevious members.p_CanGoPrevious;
        property_r_info p_CanPause members.p_CanPause;
        property_r_info p_CanPlay members.p_CanPlay;
        property_r_info p_CanSeek members.p_CanSeek;
        property_rw_info p_LoopStatus (fst members.p_LoopStatus) (snd members.p_LoopStatus);
        property_r_info p_MaximumRate members.p_MaximumRate;
        property_r_info p_Metadata members.p_Metadata;
        property_r_info p_MinimumRate members.p_MinimumRate;
        property_r_info p_PlaybackStatus members.p_PlaybackStatus;
        property_r_info p_Position members.p_Position;
        property_rw_info p_Rate (fst members.p_Rate) (snd members.p_Rate);
        property_rw_info p_Shuffle (fst members.p_Shuffle) (snd members.p_Shuffle);
        property_rw_info p_Volume (fst members.p_Volume) (snd members.p_Volume);
      |]
end
