(* File auto-generated by obus-gen-interface, DO NOT EDIT. *)
open OBus_member

module Com_canonical_dbusmenu : sig
  val interface : OBus_name.interface
  val m_AboutToShow : (int32, bool) Method.t
  val m_AboutToShowGroup : (int32 list, int32 list * int32 list) Method.t
  val m_Event : (int32 * string * OBus_value.V.single * int32, unit) Method.t

  val m_EventGroup :
    ((int32 * string * OBus_value.V.single * int32) list, int32 list) Method.t

  val m_GetGroupProperties :
    ( int32 list * string list,
      (int32 * (string * OBus_value.V.single) list) list )
    Method.t

  val m_GetLayout :
    ( int32 * int32 * string list,
      int32
      * (int32 * (string * OBus_value.V.single) list * OBus_value.V.single list)
    )
    Method.t

  val m_GetProperty : (int32 * string, OBus_value.V.single) Method.t
  val s_ItemActivationRequested : (int32 * int32) Signal.t

  val s_ItemsPropertiesUpdated :
    ((int32 * (string * OBus_value.V.single) list) list
    * (int32 * string list) list)
    Signal.t

  val s_LayoutUpdated : (int32 * int32) Signal.t
  val p_IconThemePath : (string list, [ `readable ]) Property.t
  val p_Status : (string, [ `readable ]) Property.t
  val p_TextDirection : (string, [ `readable ]) Property.t
  val p_Version : (int32, [ `readable ]) Property.t

  type 'a members = {
    m_AboutToShow : 'a OBus_object.t -> int32 -> bool Lwt.t;
    m_AboutToShowGroup :
      'a OBus_object.t -> int32 list -> (int32 list * int32 list) Lwt.t;
    m_Event :
      'a OBus_object.t ->
      int32 * string * OBus_value.V.single * int32 ->
      unit Lwt.t;
    m_EventGroup :
      'a OBus_object.t ->
      (int32 * string * OBus_value.V.single * int32) list ->
      int32 list Lwt.t;
    m_GetGroupProperties :
      'a OBus_object.t ->
      int32 list * string list ->
      (int32 * (string * OBus_value.V.single) list) list Lwt.t;
    m_GetLayout :
      'a OBus_object.t ->
      int32 * int32 * string list ->
      (int32
      * (int32 * (string * OBus_value.V.single) list * OBus_value.V.single list))
      Lwt.t;
    m_GetProperty :
      'a OBus_object.t -> int32 * string -> OBus_value.V.single Lwt.t;
    p_IconThemePath : 'a OBus_object.t -> string list React.signal;
    p_Status : 'a OBus_object.t -> string React.signal;
    p_TextDirection : 'a OBus_object.t -> string React.signal;
    p_Version : 'a OBus_object.t -> int32 React.signal;
  }

  val make : 'a members -> 'a OBus_object.interface
end

module Org_kde_StatusNotifierItem : sig
  val interface : OBus_name.interface
  val m_Scroll : (int32 * string, unit) Method.t
  val m_SecondaryActivate : (int32 * int32, unit) Method.t
  val m_XAyatanaSecondaryActivate : (int32, unit) Method.t
  val s_NewAttentionIcon : unit Signal.t
  val s_NewIcon : unit Signal.t
  val s_NewIconThemePath : string Signal.t
  val s_NewStatus : string Signal.t
  val s_NewTitle : unit Signal.t
  val s_XAyatanaNewLabel : (string * string) Signal.t
  val p_AttentionAccessibleDesc : (string, [ `readable ]) Property.t
  val p_AttentionIconName : (string, [ `readable ]) Property.t
  val p_Category : (string, [ `readable ]) Property.t
  val p_IconAccessibleDesc : (string, [ `readable ]) Property.t
  val p_IconName : (string, [ `readable ]) Property.t
  val p_IconThemePath : (string, [ `readable ]) Property.t
  val p_Id : (string, [ `readable ]) Property.t
  val p_Menu : (OBus_path.t, [ `readable ]) Property.t
  val p_Status : (string, [ `readable ]) Property.t
  val p_Title : (string, [ `readable ]) Property.t
  val p_XAyatanaLabel : (string, [ `readable ]) Property.t
  val p_XAyatanaLabelGuide : (string, [ `readable ]) Property.t
  val p_XAyatanaOrderingIndex : (int32, [ `readable ]) Property.t

  type 'a members = {
    m_Scroll : 'a OBus_object.t -> int32 * string -> unit Lwt.t;
    m_SecondaryActivate : 'a OBus_object.t -> int32 * int32 -> unit Lwt.t;
    m_XAyatanaSecondaryActivate : 'a OBus_object.t -> int32 -> unit Lwt.t;
    p_AttentionAccessibleDesc : 'a OBus_object.t -> string React.signal;
    p_AttentionIconName : 'a OBus_object.t -> string React.signal;
    p_Category : 'a OBus_object.t -> string React.signal;
    p_IconAccessibleDesc : 'a OBus_object.t -> string React.signal;
    p_IconName : 'a OBus_object.t -> string React.signal;
    p_IconThemePath : 'a OBus_object.t -> string React.signal;
    p_Id : 'a OBus_object.t -> string React.signal;
    p_Menu : 'a OBus_object.t -> OBus_path.t React.signal;
    p_Status : 'a OBus_object.t -> string React.signal;
    p_Title : 'a OBus_object.t -> string React.signal;
    p_XAyatanaLabel : 'a OBus_object.t -> string React.signal;
    p_XAyatanaLabelGuide : 'a OBus_object.t -> string React.signal;
    p_XAyatanaOrderingIndex : 'a OBus_object.t -> int32 React.signal;
  }

  val make : 'a members -> 'a OBus_object.interface
end

module Org_mpris_MediaPlayer2 : sig
  val interface : OBus_name.interface
  val m_Quit : (unit, unit) Method.t
  val m_Raise : (unit, unit) Method.t
  val p_CanQuit : (bool, [ `readable ]) Property.t
  val p_CanRaise : (bool, [ `readable ]) Property.t
  val p_CanSetFullscreen : (bool, [ `readable ]) Property.t
  val p_DesktopEntry : (string, [ `readable ]) Property.t
  val p_HasTrackList : (bool, [ `readable ]) Property.t
  val p_Identity : (string, [ `readable ]) Property.t
  val p_SupportedMimeTypes : (string list, [ `readable ]) Property.t
  val p_SupportedUriSchemes : (string list, [ `readable ]) Property.t

  type 'a members = {
    m_Quit : 'a OBus_object.t -> unit -> unit Lwt.t;
    m_Raise : 'a OBus_object.t -> unit -> unit Lwt.t;
    p_CanQuit : 'a OBus_object.t -> bool React.signal;
    p_CanRaise : 'a OBus_object.t -> bool React.signal;
    p_CanSetFullscreen : 'a OBus_object.t -> bool React.signal;
    p_DesktopEntry : 'a OBus_object.t -> string React.signal;
    p_HasTrackList : 'a OBus_object.t -> bool React.signal;
    p_Identity : 'a OBus_object.t -> string React.signal;
    p_SupportedMimeTypes : 'a OBus_object.t -> string list React.signal;
    p_SupportedUriSchemes : 'a OBus_object.t -> string list React.signal;
  }

  val make : 'a members -> 'a OBus_object.interface
end

module Org_mpris_MediaPlayer2_Player : sig
  val interface : OBus_name.interface
  val m_Next : (unit, unit) Method.t
  val m_OpenUri : (string, unit) Method.t
  val m_Pause : (unit, unit) Method.t
  val m_Play : (unit, unit) Method.t
  val m_PlayPause : (unit, unit) Method.t
  val m_Previous : (unit, unit) Method.t
  val m_Seek : (int64, unit) Method.t
  val m_SetPosition : (OBus_path.t * int64, unit) Method.t
  val m_Stop : (unit, unit) Method.t
  val s_Seeked : int64 Signal.t
  val p_CanControl : (bool, [ `readable ]) Property.t
  val p_CanGoNext : (bool, [ `readable ]) Property.t
  val p_CanGoPrevious : (bool, [ `readable ]) Property.t
  val p_CanPause : (bool, [ `readable ]) Property.t
  val p_CanPlay : (bool, [ `readable ]) Property.t
  val p_CanSeek : (bool, [ `readable ]) Property.t
  val p_LoopStatus : (string, [ `readable | `writable ]) Property.t
  val p_MaximumRate : (float, [ `readable ]) Property.t

  val p_Metadata :
    ((string * OBus_value.V.single) list, [ `readable ]) Property.t

  val p_MinimumRate : (float, [ `readable ]) Property.t
  val p_PlaybackStatus : (string, [ `readable ]) Property.t
  val p_Position : (int64, [ `readable ]) Property.t
  val p_Rate : (float, [ `readable | `writable ]) Property.t
  val p_Shuffle : (bool, [ `readable | `writable ]) Property.t
  val p_Volume : (float, [ `readable | `writable ]) Property.t

  type 'a members = {
    m_Next : 'a OBus_object.t -> unit -> unit Lwt.t;
    m_OpenUri : 'a OBus_object.t -> string -> unit Lwt.t;
    m_Pause : 'a OBus_object.t -> unit -> unit Lwt.t;
    m_Play : 'a OBus_object.t -> unit -> unit Lwt.t;
    m_PlayPause : 'a OBus_object.t -> unit -> unit Lwt.t;
    m_Previous : 'a OBus_object.t -> unit -> unit Lwt.t;
    m_Seek : 'a OBus_object.t -> int64 -> unit Lwt.t;
    m_SetPosition : 'a OBus_object.t -> OBus_path.t * int64 -> unit Lwt.t;
    m_Stop : 'a OBus_object.t -> unit -> unit Lwt.t;
    p_CanControl : 'a OBus_object.t -> bool React.signal;
    p_CanGoNext : 'a OBus_object.t -> bool React.signal;
    p_CanGoPrevious : 'a OBus_object.t -> bool React.signal;
    p_CanPause : 'a OBus_object.t -> bool React.signal;
    p_CanPlay : 'a OBus_object.t -> bool React.signal;
    p_CanSeek : 'a OBus_object.t -> bool React.signal;
    p_LoopStatus :
      ('a OBus_object.t -> string React.signal)
      * ('a OBus_object.t -> string -> unit Lwt.t);
    p_MaximumRate : 'a OBus_object.t -> float React.signal;
    p_Metadata :
      'a OBus_object.t -> (string * OBus_value.V.single) list React.signal;
    p_MinimumRate : 'a OBus_object.t -> float React.signal;
    p_PlaybackStatus : 'a OBus_object.t -> string React.signal;
    p_Position : 'a OBus_object.t -> int64 React.signal;
    p_Rate :
      ('a OBus_object.t -> float React.signal)
      * ('a OBus_object.t -> float -> unit Lwt.t);
    p_Shuffle :
      ('a OBus_object.t -> bool React.signal)
      * ('a OBus_object.t -> bool -> unit Lwt.t);
    p_Volume :
      ('a OBus_object.t -> float React.signal)
      * ('a OBus_object.t -> float -> unit Lwt.t);
  }

  val make : 'a members -> 'a OBus_object.interface
end
